swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /formulario_por_tipo/:
    get:
      tags:
      - formulario_por_tipo
      description: Consultar los formularios por tipo id tercero y periodo
      operationId: Formulario_por_tipoController.GetFormularioTipo
      parameters:
      - in: query
        name: id_tipo_formulario
        description: Id del tipo formulario
        type: string
      - in: query
        name: id_periodo
        description: Id del periodo
        type: string
      - in: query
        name: id_tercero
        description: Id del tercero
        type: string
      - in: query
        name: id_espacio
        description: Id del espacio
        type: string
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
  /respuesta_formulario/:
    post:
      tags:
      - respuesta_formulario
      description: create Respuesta_formulario
      operationId: Respuesta_formularioController.PostRespuestaFormulario
      parameters:
      - in: body
        name: body
        description: body for Respuesta_formulario content
        required: true
        schema:
          $ref: '#/definitions/models.Respuesta_formulario'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Respuesta_formulario'
        "403":
          description: body is empty
definitions:
  models.Respuesta_formulario:
    title: Respuesta_formulario
    type: object
tags:
- name: formulario_por_tipo
  description: |
    Formulario_por_tipoController operations for Formulario_por_tipo
- name: respuesta_formulario
  description: |
    Respuesta_formularioController operations for Respuesta_formulario
