appname = sga_evaluacion_docente_mid
httpport = ${SGA_EVALUACION_DOCENTE_MID_HTTP_PORT}
runmode = dev
autorender = false
copyrequestbody = true

EvaluacionDocenteService = ${EVALUACION_DOCENTE_SERVICE}
ParametrosService = ${PARAMETROS_SERVICE}
PlanDocenteService = ${PLAN_DOCENTE_SERVICE}
UrlWSO2=${EVALUACION_DOCENTE_MID_WSO2_URL}
NsAcademica=${EVALUACION_DOCENTE_MID_WSO2_ACADEMICA}
AcademicaJbpm=${ACADEMICA_JBPM}
GestorDocumentalService = ${GESTOR_DOCUMENTAL_MID}
NotificacionService = ${NOTIFICACION_MID}